### ISSUE TITLE
How do you style the picker?

### ISSUE THREAD

**Issue by Thorbenandresen** [puredazzle/react-native-simple-picker#1]
Hi!

thanks for making this!

In your example gif the picker is styled (bronze colors), but the example app renders and unstyled picker.

Some props for styling would be great.

**Comment by puredazzle** [comment]
Hi!

I think that it is just because of the GIF, it makes the color a little bit strange.

But I can add props for styling. :)

**Comment by puredazzle** [comment]
I have added the itemStyle as a prop now. Updated version is here and on NPM. Have updated the `exampleApp` also.

**Comment by vinkla** [comment]
@Thorbenandresen please see this commit 38c5808603797b4dc9a780d0bc49f9cf72f74516.
