### ISSUE TITLE
buttonStyle prop does not work,

### ISSUE THREAD

**Issue by tolgaatam** [puredazzle/react-native-simple-picker#13]
buttonStyle prop do not work somehow. By examining the code, one would think that it should work. But when i inspect, i see that somehow the style property for buttons is overriden by

{
    color: "#007AFF"
}

automatically. what could be the reason for such default value?

**Comment by puredazzle** [comment]
@tolgaatam hi! could you please provide a full example of the code you are using for the picker?

**Comment by tolgaatam** [comment]
hey,

here is how i use the picker

`<SimplePicker
					ref={'picker'}
					options={languageKeys}
					labels={languageLabels}
					buttonStyle={{
						fontSize: 100
					}}
					itemStyle={{
						fontSize: 22,
						fontWeight: 'bold',
					}}
					onSubmit={(option) =>{
						this.setState({
							language: option,
						});
					}}
				/>`

itemStyle works but no luck for buttonStyle

**Comment by puredazzle** [comment]
@mateioprea could you take a look at this? do you have any input?

**Comment by tolgaatam** [comment]
seems like updating to the latest solves the problem.

after 4 days ago's merge, buttonColor was replaced by buttonStyle and now it is usable i guess.
worksforme

**Comment by puredazzle** [comment]
@tolgaatam ok, great. I will close this issue now then.

**Comment by mateioprea** [comment]
@puredazzle maybe we should somehow default to old settings?

**Comment by puredazzle** [comment]
@mateioprea maybe we can add a message that the buttonColor is deprecated and that the user should use buttonStyle instead?
