### ISSUE TITLE
initial chosen not supported

### ISSUE THREAD

**Issue by tolgaatam** [puredazzle/react-native-simple-picker#14]
everytime we choose a new value and close the modal, reopening the modal result in auto choosing the previous value because it is stored in the state of the component. that is totally how it should be. but, whether we give an initial value or not, the chosen item is set to be the zeroth element of the options, which is not useful.

**Comment by mateioprea** [comment]
@puredazzle maybe adding a param named ```initialOptionIndex``` can help with it. What do you think? Or maybe the option to select based on index or label?

**Comment by puredazzle** [comment]
yes, that sounds good! I will update and push.
