### ISSUE TITLE
React PropTypes warning

### ISSUE THREAD

**Issue by spinningarrow** [puredazzle/react-native-simple-picker#18]
I'm getting the following warning from React when I use the Simple Picker:

```
Warning: PropTypes has been moved to a separate package. Accessing React.PropTypes is no longer supported and will be removed completely in React 16. Use the prop-types package on npm instead. 
```

Can this be fixed? I'd be happy to make a PR to fix this; should be an easy change.

**Comment by mateioprea** [comment]
Hey @spinningarrow. Yes, the easy fix is to install the new prop-types package and 
import PropTypes from 'prop-types'.

Remember that react 16 is not stable yet and this change will happen in the future. You can submit a PR with this.

**Comment by spinningarrow** [comment]
Cool, I'll submit a PR. Yes, React 16 is not stable but the deprecation warning is already preset in newer versions of React 15 iirc.
