### ISSUE TITLE
Styling for the picker

### ISSUE THREAD

**Issue by jophyson93** [puredazzle/react-native-simple-picker#2]
Is there  a way to change the styling of the picker? like the picker background, color of the cancel/confirm buttons, etc. Thanks!

**Comment by puredazzle** [comment]
Hi! It is possible to change the color of the buttons via props `buttonColor` on the picker. Here is the code in the `index.js`where it sets the color: https://github.com/puredazzle/react-native-simple-picker/blob/master/index.js#L58 – the background color is not possible to change atm but it is definitely  possible to add!
