### ISSUE TITLE
example is distributed over npm

### ISSUE THREAD

**Issue by vonovak** [puredazzle/react-native-simple-picker#21]
should be added to npmignore

**Comment by vinkla** [comment]
[No it isn't?](https://docs.npmjs.com/files/package.json#files)

https://github.com/puredazzle/react-native-simple-picker/blob/a73236a8f8f0a3358e7bb69c5dbc962a81e034d8/package.json#L20-L22

**Comment by vinkla** [comment]
@vonovak please write better issues in the future. Write a good title and write much more thorough descriptions. Think of it like this; we're spending our free time to working on this repository. We don't want to spend too much time trying to understanding cryptic issues. Spend more time describing the issue or better yet, submit a pull request.

**Comment by vonovak** [comment]
my apologies, I didn't realize I was pulling the code from my own fork
