### ISSUE TITLE
after scrolling its automatically resets to starting item

### ISSUE THREAD

**Issue by chiragkukreja** [puredazzle/react-native-simple-picker#22]
i have an array of 50 objects which i am displaying in picker view. After scrolling to particular item it automatically scroll to starting position  means first item and due to this am not able to select particular item

**Comment by puredazzle** [comment]
@chiragkukreja thanks for your issue. since we are using the `PickerIOS` from `react-native` could you maybe do a test with only the `PickerIOS` and 50+ items to see if it is something with our script or with the script we are pulling in from `react-native`.

**Comment by puredazzle** [comment]
Closing this issue. Please provide a fiddle with just a pure PickerIOS so we can isolate the issue.
