### ISSUE TITLE
Issue with picking item while scrolling is in progress

### ISSUE THREAD

**Issue by stobe1** [puredazzle/react-native-simple-picker#28]
If you click confirm, while scrolling is in progress, it wont select any item, and even more, picker wont fire onSubmit event no more after that, until you unmount it.

**Comment by puredazzle** [comment]
@stobe1 I have noticed this also, but from what I understand this is an issue with the picker from React Native and how it functions. We use https://facebook.github.io/react-native/docs/picker.html and if you try this separately you will get the same behaviour. If you know any fix to this, please make an PR. Thanks!
