### ISSUE TITLE
Changing overlay background opacity

### ISSUE THREAD

**Issue by grigorigoldman** [puredazzle/react-native-simple-picker#32]
I wanted to tweak the opacity of the overlay, so that there's a visual indication that the screen is not editable. Changing the background colour/opacity of the `overlayContainer` kind of lets me do that but when the picker opens because of the `slide` animation type you can actually see the overlay rising.

I think a better way would be if the overlay appeared first without slide animation and then the picker slid into view.

Do you have any thoughts on how this could be achieved? 

I tried a simple approach of moving the overlay view out of the modal but then the overlay won't cover the navigation bar.

I am thinking maybe nesting modals, e.g. open outer modal with the overlay but no animation, then open inner modal with the picker. It seems kind of hacky to me and I'm not even sure that it would work.

**Comment by mateioprea** [comment]
Hi @grigorigoldman, can you post an example of what you're trying to achieve?

**Comment by grigorigoldman** [comment]
The code looks like something like this:
```
<SimplePicker
  ref={'picker'}
  options={options}
  styles={{
    overlayContainer: {
      flex: 1,
      width: SCREEN_WIDTH,
      backgroundColor: 'rgba(192,192,192,0.2)',
    }
  }}
/>
```
![screen recording 2018-07-06 at 12 12 pm](https://user-images.githubusercontent.com/2268933/42356502-2bec2118-8116-11e8-9857-9cc0f5ee73ab.gif)

**Comment by grigorigoldman** [comment]
OK, after thinking about it for a bit and checking how others have tackled this problem, the only solution that I can think of is not using the `slide` animation of the modal. Instead we can implement it manually using RN's Animated library.

I tweaked the code to test this out. Here's what I've done so far:

```
const SCREEN_WIDTH = Dimensions.get('window').width;
const SCREEN_HEIGHT = Dimensions.get('window').height;

const styles = {
  ....
  overlayContainer: {
    width: SCREEN_WIDTH,
    height: SCREEN_HEIGHT,
    zIndex: -1,
  },
  .....
}
constructor(props) {
 ......
  this.state = {
    modalVisible: props.modalVisible || false,
    selectedOption: props.options[selected],
    translateY: new Animated.Value(0),
  };
  .....
}

show() {
   this.setState({
     modalVisible: true,
    });
    Animated.timing(
      this.state.translateY,
      { toValue: -250 }
    ).start();
}

hide() {
    Animated.timing(
      this.state.translateY,
      { toValue: 0 }
    ).start(() => this.setState({ modalVisible: false }));
}

render() {
    const { modalVisible, selectedOption, translateY } = this.state;
    const {
      options,
      buttonStyle,
      itemStyle,
      cancelText,
      cancelTextStyle,
      confirmText,
      confirmTextStyle,
      disableOverlay,
    } = this.props;


    return (
      <Modal transparent={true} visible={this.state.modalVisible}>
        <TouchableWithoutFeedback onPress={this.onOverlayDismiss}>
          <View style={this.styles.overlayContainer}/>
        </TouchableWithoutFeedback>
        <Animated.View style={[this.styles.modalContainer, {transform: [{translateY}]}]}>
          <View style={this.styles.buttonView}>
            <TouchableOpacity onPress={this.onPressCancel}>
              <Text style={[buttonStyle, cancelTextStyle]}>
                {cancelText || 'Cancel'}
              </Text>
            </TouchableOpacity>
            <TouchableOpacity onPress={this.onPressSubmit}>
              <Text style={[buttonStyle, confirmTextStyle]}>
                {confirmText || 'Confirm'}
              </Text>
            </TouchableOpacity>
          </View>
          <View style={this.styles.mainBox}>
            <Picker
              style={this.styles.bottomPicker}
              selectedValue={selectedOption}
              onValueChange={option => this.onValueChange(option)}
              itemStyle={itemStyle}
            >
              {options.map((option, index) => this.renderItem(option, index))}
            </Picker>
          </View>
        </Animated.View>
      </Modal>
    );
  }
}
```
Not sure how this will work across iOS and Android, different screen sizes, etc, but could be a way to go.

**Comment by puredazzle** [comment]
@grigorigoldman great work. I am currently away on summer vacation :) – but it would be great with a PR for us to test either way around. 

Just a quick thought. A different way would be to add two user callbacks to `show()` and `hide()` so the user can specify different actions depending on their specific needs. What are your thoughts regarding this?

**Comment by grigorigoldman** [comment]
@puredazzle please see PR https://github.com/puredazzle/react-native-simple-picker/pull/34

I'll play around with your idea of `onShow()` and `onHide()` and see if I can get the same effect.

**Comment by grigorigoldman** [comment]
I ended up with 4 callbacks actually, e.g.

`onShow()` and `onHide()` get called from the `show()` and `hide()` functions, and
`onShown()` and `onHidden()` are wired into the Modal's `onShow` and `onDismiss` props.

The difference is, the first two are triggered before the actual action completes, i.e. before the modal is actually shown/hidden. The other two get triggered once the action is over, i.e. the modal is completely rendered or hidden.

I still couldn't get the same behaviour as in https://github.com/puredazzle/react-native-simple-picker/pull/34. When the modal is displayed there is small but perceptible lag between when it's fully rendered and when the overlay changes colour/opacity. And when hiding the modal, I couldn't get the overlay colour to change properly, so you could see the edge sliding down (as in my first example).

The picker code looks like this (customStyles contains the overlay background colour override):
```
<SimplePicker
  ref={'picker'}
  options={options}
  onSubmit={(option) => {
    this.setState({
      selectedOption: option,
    });
  }}
  onShown={() => this.setState({shown: true})}
  onHide={() => this.setState({shown: false})}
  styles={this.state.shown ? customStyles : defaultStyles}
/>
```

![screen recording 2018-07-18 at 06 10 pm](https://user-images.githubusercontent.com/2268933/42868554-f5579eb2-8ab5-11e8-93fe-02ca4bd22e02.gif)

**Comment by puredazzle** [comment]
@grigorigoldman ah, I understand the problem. I thought that maybe you could use the callbacks (as you do) to set a state and then have a different layer that is not the SimplePicker but a `<View>` which is visible depending on the state `{this.state.shown && <View style={this.styles.backgroundOverlay} />}`. The overlay-view will be visible between your content and the picker. Do you think this would work?

The reason I like the idea of `onShow()` etc is because then the user can control what they want to happen. For example some users might want to blur a specific block when the picker is shown.

**Comment by grigorigoldman** [comment]
@puredazzle that's a good idea and I did try it. Unfortunately, in my app, I am also using the `react-navigation` library and what's happening is that the background overlay doesn't cover the  nav header. The problem is discussed here: https://github.com/react-navigation/react-navigation/issues/363.

The only practical solutions that were suggested was to either use a `Modal` component or to place the overlay `View` at the root of the app, which is not ideal for the picker use case.

I suppose it's not really a picker issue but `react-navigation` is a reasonably popular library so I suspect at some point someone else will stumble across this issue. 🤷‍♂️

**Comment by puredazzle** [comment]
@grigorigoldman ah ok, then I understand. I think it is still good to have onShow onHide, but we could merge your PR if we could do some testing in iOS and Android because this PR is a bigger change to the code. @mateioprea and @grigorigoldman  could you do a test in Android? It would be very helpful!

**Comment by grigorigoldman** [comment]
Did some testing on Android, here's what it looks like on my emulator:

![screen recording 2018-08-10 at 05 20 pm](https://user-images.githubusercontent.com/2268933/43944385-0a847e2c-9cc2-11e8-9b1e-6308afe2751a.gif)

/cc @puredazzle @mateioprea @vinkla 

PS: The exampleApp seems to be out of date, I had some issues getting it going to do this testing. Is it just me? If not, I am happy to create another PR to update it (let me know).

**Comment by puredazzle** [comment]
@grigorigoldman great work! I will merge this and release it as a new major version.

It would be very appreciated if you would like to make a PR for the exampleApp also! Godspeed!
