### ISSUE TITLE
Missing required prop onRequestClose warning on Android

### ISSUE THREAD

**Issue by grigorigoldman** [puredazzle/react-native-simple-picker#35]
This is related to this question https://github.com/puredazzle/react-native-simple-picker/issues/33

I'm getting the following warning message when rendering the modal:
"Warning: Failed prop type: Required prop
`onRequestClose` was not specified in the `Modal`"

Sure enough, according to the react-native docs the `onRequestClose` callback is mandatory for Android. It's called when a hardware back button is pressed.

I think it's an easy fix. We can hook it up to the `onPressCancel()` function. I'm happy to create a PR for this.

But, since I was already poking around in the Android space, I took a look at how it actually looks and functions. The UX doesn't look quite right to me, this is what it looks like:

![android](https://user-images.githubusercontent.com/2268933/42679241-9c87223e-86c4-11e8-959e-66713014ae86.gif)

Is this intentional? I'm thinking it should probably just expand to the full view when picker opens. Thoughts?

**Comment by SoiTrang** [comment]
I have the same issue with [grigorigoldman](https://github.com/grigorigoldman) on Android

**Comment by puredazzle** [comment]
@grigorigoldman thanks for your work. I will merge as soon as I get back to the office again. @mateioprea do you have any comments regarding the UX here. I think this is how the picker looks on Android but the cross compability was added by another contributed.

**Comment by mateioprea** [comment]
@puredazzle maybe it should act exactly how the native android picker does. What do you think? Or the scope is to have it like on iOS?

**Comment by puredazzle** [comment]
@mateioprea I think it should act as the Picker component from React Native acts by default. That way we remove a lot of errors/bugs for the future. So I guess the screenshot above is what Android users are familiar with.

**Comment by grigorigoldman** [comment]
I agree keeping it as close to default as possible is the best way forward.

I think that on Android, the picker is more of a form input field, like a mix of a TextInput and a dropdown, that's why it renders that little arrow-down icon on the right. 

I'm thinking that the "input field" view of the picker should always be visible. Maybe it's not quite right to attach the picker to a text label like in the example.

Also, there is probably no need for the Cancel and Confirm buttons. I think the default behaviour is, as soon as the user clicks an option in the picker modal, it closes the modal and updates the field.

**Comment by puredazzle** [comment]
@grigorigoldman I have merged https://github.com/puredazzle/react-native-simple-picker/pull/36 and will publish to NPM today. Thanks for the help! We will keep the picker as it is for Android for the time being. If we should change this I think it should be its own issue.

**Comment by grigorigoldman** [comment]
@puredazzle sure, sounds good. I'm mostly working on IOS at the moment but once I'll start looking at android, maybe I'll have a better idea on what to do... if anything
