### ISSUE TITLE
Landscape orientation is not supporting.

### ISSUE THREAD

**Issue by mssureshmewara** [puredazzle/react-native-simple-picker#39]
OK and Cancel Text disappears when orientation change from portrait to landscape.

**Comment by puredazzle** [comment]
@mssureshmewara thanks! I guess this PR fixes the issue? https://github.com/puredazzle/react-native-simple-picker/pull/40 – it would be great if you could make a PR just for the supportedOrientations.

**Comment by puredazzle** [comment]
Merged in #40
