### ISSUE TITLE
Issue style

### ISSUE THREAD

**Issue by HaoCao216** [puredazzle/react-native-simple-picker#44]
![screenshot from 2019-03-04 21-48-01](https://user-images.githubusercontent.com/30788506/53741170-5dd2fb00-3ec8-11e9-832d-acd803cb378a.png)

Its not get wheel style like demo, please help me reslove it. Tks so much!

**Comment by puredazzle** [comment]
Please post a new issue with more information.

> When a person reviews an Issue Request there should be enough information that they have a good handle of what is being discussed, they don’t need to know or come up with a solution instantly, but nothing about the issue should be mystery meat - [UpThemes](https://upthemes.com/blog/2014/02/writing-useful-github-issues/)

**Comment by puredazzle** [comment]
Please also provide a link or code from your project for us to view. Thanks!

**Comment by HaoCao216** [comment]
> Please also provide a link or code from your project for us to view. Thanks!

I just follow your example. But my select option not show like your demo ( like photo above )
