### ISSUE TITLE
Wheel select options not working

### ISSUE THREAD

**Issue by HaoCao216** [puredazzle/react-native-simple-picker#45]
![screenshot from 2019-03-04 22-08-31](https://user-images.githubusercontent.com/30788506/53742152-8fe55c80-3eca-11e9-85e0-fd42fa0633ba.png)
![screenshot from 2019-03-04 22-11-34](https://user-images.githubusercontent.com/30788506/53742157-92e04d00-3eca-11e9-89df-2c258277c0cd.png)
Hi, Can you see 2 pics, it has the difference between select options ( wheel and not ).How can I make select option (wheel style) like exsample?

**Comment by puredazzle** [comment]
@HaoCao216 Hi! Thanks for your question. The screenshot provided is when the component is used in an iOS environment. You can see a previous conversation regarding the picker design for Android in this issue: https://github.com/puredazzle/react-native-simple-picker/issues/35

Please let me know if you have any other questions!

**Comment by HaoCao216** [comment]
> @HaoCao216 Hi! Thanks for your question. The screenshot provided is when the component is used in an iOS environment. You can see a previous conversation regarding the picker design for Android in this issue: #35
> 
> Please let me know if you have any other questions!

I got it. Thanks you so much
