### ISSUE TITLE
Picker is not working in android devices.

### ISSUE THREAD

**Issue by anshumanburman** [puredazzle/react-native-simple-picker#47]
Picker is not working in android device. Please tell me how to use this picker in android device too?

**Comment by puredazzle** [comment]
Please post a new issue with more information.

> When a person reviews an Issue Request there should be enough information that they have a good handle of what is being discussed, they don’t need to know or come up with a solution instantly, but nothing about the issue should be mystery meat - [UpThemes](https://upthemes.com/blog/2014/02/writing-useful-github-issues/)
