### ISSUE TITLE
How to integrate with redux-form

### ISSUE THREAD

**Issue by Suresh-R-S** [puredazzle/react-native-simple-picker#5]
Hi,

How can we integrate this picker with redux-form

**Comment by puredazzle** [comment]
Hello,

Could you please provide an example of your app? It shouldn't be any problems to connect this with a redux solution. You could pass the props from the redux via the parent wrapper for a simple solution.

**Comment by Suresh-R-S** [comment]
Hey Thanks..
I wrapped SimplePicker inside a component, and in that component file I did :

`<SimplePicker ref = {'picker'} options = {options} onSubmit = { (option) => input.onChange(option)} {...input}></SimplePicker>`

i.e. proper onSubmit was needed 👍 
Hope it helps someone.
