### ISSUE TITLE
 Invariant Violation: requireNativeComponent: "RNCAndroidDialogPicker" was not found in the UIManager.

### ISSUE THREAD

**Issue by Ziamuhyuddin** [puredazzle/react-native-simple-picker#50]
I am using this library in react native environment. This error occurs on an android device. Error statement is like,
 Invariant Violation: requireNativeComponent: "RNCAndroidDialogPicker" was not found in the UIManager.

**Comment by puredazzle** [comment]
Please post a new issue with more information.

> When a person reviews an Issue Request there should be enough information that they have a good handle of what is being discussed, they don’t need to know or come up with a solution instantly, but nothing about the issue should be mystery meat - [UpThemes](https://upthemes.com/blog/2014/02/writing-useful-github-issues/)

**Comment by sunjun2009311** [comment]
I also encountered the same problem when I first used it

>  ERROR  Invariant Violation: requireNativeComponent: "RNCAndroidDialogPicker" was not found in the UIManager.

This error is located at:
    in RNCAndroidDialogPicker
    in PickerAndroid (created by Picker)
    in Picker (created by SimplePicker)
    in RCTView (created by View)
    in View (created by SimplePicker)
    in RCTView (created by View)
    in View
